version: "3.8"
services:
  backend:
    build: .
    container_name: perfume-backend
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - ./uploads:/app/public/uploads
      - ./.tmp:/app/.tmp
      - ./database:/app/database
    restart: always
